import { Destination } from '../types';

export const destinationDatabase: Destination[] = [
  {
    id: '1',
    name: 'Barcelona',
    country: 'Spain',
    continent: 'europe',
    vacationType: ['city break'],
    description: 'A vibrant coastal city blending stunning architecture by Gaudí, beautiful beaches, and a thriving culinary scene.',
    temperature: 'warm',
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
    imageQuery: 'barcelona spain sagrada familia',
    budget: 'moderate',
    activities: ['Architecture Tours', 'Beach Relaxing', 'Food & Wine', 'Museums'],
    highlights: ['Sagrada Familia', 'Park Güell', 'La Rambla', 'Gothic Quarter'],
    travelTip: 'Book Sagrada Familia tickets in advance. Visit early morning to avoid crowds.',
    flightDuration: '0-4',
    coordinates: { lat: 41.3874, lng: 2.1686 }
  },
  {
    id: '2',
    name: 'Prague',
    country: 'Czech Republic',
    continent: 'europe',
    vacationType: ['city break'],
    description: 'A fairytale city with medieval architecture, charming cobblestone streets, and historic castles.',
    temperature: 'cool',
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
    imageQuery: 'prague czech republic castle',
    budget: 'budget',
    activities: ['Castle Tours', 'River Cruise', 'Beer Tasting', 'Walking Tours'],
    highlights: ['Prague Castle', 'Charles Bridge', 'Old Town Square', 'Astronomical Clock'],
    travelTip: 'Prague is very walkable. Stay in Old Town for easy access to main attractions.',
    flightDuration: '0-4',
    coordinates: { lat: 50.0755, lng: 14.4378 }
  },
  {
    id: '3',
    name: 'Amsterdam',
    country: 'Netherlands',
    continent: 'europe',
    vacationType: ['city break'],
    description: 'A picturesque city known for its artistic heritage, elaborate canal system, and narrow houses.',
    temperature: 'cool',
    bestMonths: ['April', 'May', 'June', 'July', 'August', 'September'],
    imageQuery: 'amsterdam canals netherlands',
    budget: 'moderate',
    activities: ['Canal Cruises', 'Cycling', 'Museum Hopping', 'Cafe Culture'],
    highlights: ['Anne Frank House', 'Van Gogh Museum', 'Canal Ring', 'Jordaan District'],
    travelTip: 'Rent a bike to explore like a local. Book Anne Frank House months in advance.',
    flightDuration: '0-4',
    coordinates: { lat: 52.3676, lng: 4.9041 }
  },
  {
    id: '4',
    name: 'Santorini',
    country: 'Greece',
    continent: 'europe',
    vacationType: ['sea'],
    description: 'A stunning volcanic island with iconic white-washed buildings, blue-domed churches, and breathtaking sunsets.',
    temperature: 'warm',
    bestMonths: ['May', 'June', 'July', 'August', 'September', 'October'],
    imageQuery: 'santorini greece sunset',
    budget: 'luxury',
    activities: ['Sunset Watching', 'Wine Tasting', 'Beach Hopping', 'Photography'],
    highlights: ['Oia Sunset', 'Red Beach', 'Caldera Views', 'Ancient Akrotiri'],
    travelTip: 'Stay in Oia for sunsets, but Fira offers better value. Visit in shoulder season.',
    flightDuration: '0-4',
    coordinates: { lat: 36.3932, lng: 25.4615 }
  },
  {
    id: '5',
    name: 'Algarve',
    country: 'Portugal',
    continent: 'europe',
    vacationType: ['sea'],
    description: 'Portugal\'s southernmost region featuring golden beaches, dramatic cliffs, and charming fishing villages.',
    temperature: 'warm',
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    imageQuery: 'algarve portugal beach cliffs',
    budget: 'moderate',
    activities: ['Surfing', 'Golf', 'Boat Tours', 'Coastal Hiking'],
    highlights: ['Benagil Cave', 'Lagos Cliffs', 'Praia da Marinha', 'Vilamoura Marina'],
    travelTip: 'Rent a car to explore hidden beaches. Try fresh seafood in local villages.',
    flightDuration: '0-4'
  },
  {
    id: '6',
    name: 'Croatian Coast',
    country: 'Croatia',
    continent: 'europe',
    vacationType: ['sea'],
    description: 'A pristine coastline dotted with medieval towns, crystal-clear Adriatic waters, and over a thousand islands.',
    temperature: 'warm',
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    imageQuery: 'dubrovnik croatia coast',
    budget: 'moderate',
    activities: ['Island Hopping', 'Kayaking', 'Old Town Exploring', 'Game of Thrones Tours'],
    highlights: ['Dubrovnik Walls', 'Plitvice Lakes', 'Hvar Island', 'Split Palace'],
    travelTip: 'Use ferries for island hopping. Visit Dubrovnik early morning to avoid cruise crowds.',
    flightDuration: '0-4'
  },
  {
    id: '7',
    name: 'Swiss Alps',
    country: 'Switzerland',
    continent: 'europe',
    vacationType: ['mountains', 'sea'],
    description: 'Majestic mountain ranges offering world-class skiing, hiking trails, and charming alpine villages.',
    temperature: 'cold',
    bestMonths: ['June', 'July', 'August', 'December', 'January', 'February'],
    imageQuery: 'swiss alps matterhorn',
    budget: 'luxury',
    activities: ['Skiing', 'Hiking', 'Mountain Railways', 'Alpine Villages'],
    highlights: ['Matterhorn', 'Jungfraujoch', 'Lauterbrunnen Valley', 'Zermatt'],
    travelTip: 'Get Swiss Travel Pass for unlimited train travel. Summer hiking is less crowded.',
    flightDuration: '0-4',
    difficulty: 'moderate'
  },
  {
    id: '8',
    name: 'Dolomites',
    country: 'Italy',
    continent: 'europe',
    vacationType: ['mountains', 'sea'],
    description: 'Dramatic limestone peaks offering incredible hiking, skiing, and breathtaking vistas.',
    temperature: 'cool',
    bestMonths: ['June', 'July', 'August', 'September', 'December', 'January'],
    imageQuery: 'dolomites italy mountains',
    budget: 'moderate',
    activities: ['Via Ferrata', 'Hiking', 'Skiing', 'Mountain Biking'],
    highlights: ['Tre Cime', 'Alpe di Siusi', 'Cortina d\'Ampezzo', 'Lago di Braies'],
    travelTip: 'Rent a car for flexibility. Stay in mountain rifugios for authentic experience.',
    flightDuration: '0-4',
    difficulty: 'moderate'
  },
  {
    id: '9',
    name: 'Scottish Highlands',
    country: 'Scotland',
    continent: 'europe',
    vacationType: ['mountains'],
    description: 'Wild, rugged landscapes with ancient castles, mysterious lochs, and stunning glens.',
    temperature: 'cool',
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    imageQuery: 'scottish highlands mountains',
    budget: 'moderate',
    activities: ['Hiking', 'Castle Visiting', 'Whisky Tasting', 'Wildlife Watching'],
    highlights: ['Isle of Skye', 'Loch Ness', 'Ben Nevis', 'Glencoe'],
    travelTip: 'Pack waterproof gear. Drive the North Coast 500 for epic scenery.',
    flightDuration: '0-4',
    difficulty: 'easy'
  },
  {
    id: '10',
    name: 'Tokyo',
    country: 'Japan',
    continent: 'asia',
    vacationType: ['city break'],
    description: 'A mesmerizing blend of ultra-modern technology and ancient traditions.',
    temperature: 'warm',
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    imageQuery: 'tokyo japan city skyline',
    budget: 'moderate',
    activities: ['Temple Visits', 'Shopping', 'Street Food', 'Karaoke'],
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Tokyo Skytree', 'Tsukiji Market'],
    travelTip: 'Get JR Pass for travel. Visit during cherry blossom season for magical views.',
    flightDuration: '10+'
  },
  {
    id: '11',
    name: 'Bangkok',
    country: 'Thailand',
    continent: 'asia',
    vacationType: ['city break'],
    description: 'A vibrant metropolis known for ornate temples, bustling markets, and incredible street food.',
    temperature: 'hot',
    bestMonths: ['November', 'December', 'January', 'February'],
    imageQuery: 'bangkok thailand temple',
    budget: 'budget',
    activities: ['Temple Tours', 'Street Food', 'Night Markets', 'River Cruises'],
    highlights: ['Grand Palace', 'Wat Pho', 'Floating Markets', 'Chatuchak Market'],
    travelTip: 'Use BTS Skytrain to avoid traffic. Try street food for authentic experience.',
    flightDuration: '10+'
  },
  {
    id: '12',
    name: 'Singapore',
    country: 'Singapore',
    continent: 'asia',
    vacationType: ['city break'],
    description: 'A futuristic city-state blending diverse cultures, stunning architecture, and lush gardens.',
    temperature: 'hot',
    bestMonths: ['February', 'March', 'April', 'July', 'August'],
    imageQuery: 'singapore marina bay gardens',
    budget: 'luxury',
    activities: ['Gardens', 'Shopping', 'Food Courts', 'Night Safari'],
    highlights: ['Gardens by the Bay', 'Marina Bay Sands', 'Sentosa', 'Hawker Centers'],
    travelTip: 'Use MRT for easy transport. Visit hawker centers for affordable local food.',
    flightDuration: '10+'
  },
  {
    id: '13',
    name: 'Maldives',
    country: 'Maldives',
    continent: 'asia',
    vacationType: ['sea'],
    description: 'A tropical paradise of coral islands with pristine white beaches and crystal-clear turquoise waters.',
    temperature: 'hot',
    bestMonths: ['November', 'December', 'January', 'February', 'March', 'April'],
    imageQuery: 'maldives beach overwater bungalow',
    budget: 'luxury',
    activities: ['Snorkeling', 'Diving', 'Island Hopping', 'Spa Treatments'],
    highlights: ['Overwater Bungalows', 'Coral Reefs', 'Bioluminescent Beaches', 'Whale Sharks'],
    travelTip: 'All-inclusive resorts offer best value. Book water villas in advance.',
    flightDuration: '10+'
  },
  {
    id: '14',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'asia',
    vacationType: ['sea'],
    description: 'An island paradise featuring beautiful beaches, ancient temples, lush rice terraces, and vibrant culture.',
    temperature: 'hot',
    bestMonths: ['April', 'May', 'June', 'July', 'August', 'September'],
    imageQuery: 'bali indonesia beach temple',
    budget: 'budget',
    activities: ['Surfing', 'Yoga', 'Temple Visits', 'Rice Terrace Tours'],
    highlights: ['Uluwatu Temple', 'Tegallalang Rice Terraces', 'Ubud Monkey Forest', 'Seminyak Beach'],
    travelTip: 'Stay in Ubud for culture, Seminyak for beaches. Rent a scooter for flexibility.',
    flightDuration: '10+'
  },
  {
    id: '15',
    name: 'Phuket',
    country: 'Thailand',
    continent: 'asia',
    vacationType: ['sea'],
    description: 'Thailand\'s largest island offering stunning beaches, vibrant nightlife, and excellent diving spots.',
    temperature: 'hot',
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
    imageQuery: 'phuket thailand beach',
    budget: 'budget',
    activities: ['Beach Hopping', 'Diving', 'Island Tours', 'Thai Massage'],
    highlights: ['Phi Phi Islands', 'Patong Beach', 'Big Buddha', 'Old Phuket Town'],
    travelTip: 'Take day trips to nearby islands. Avoid Patong if you want quieter beaches.',
    flightDuration: '4-10'
  },
  {
    id: '16',
    name: 'Himalayas',
    country: 'Nepal',
    continent: 'asia',
    vacationType: ['mountains'],
    description: 'Home to the world\'s highest peaks including Mount Everest.',
    temperature: 'cool',
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    imageQuery: 'himalayas nepal mountains everest',
    budget: 'budget',
    activities: ['Trekking', 'Monastery Visits', 'Mountain Viewing', 'Local Culture'],
    highlights: ['Everest Base Camp', 'Annapurna Circuit', 'Pokhara', 'Kathmandu Temples'],
    travelTip: 'Hire a guide for treks. Acclimatize properly to avoid altitude sickness.',
    flightDuration: '4-10',
    difficulty: 'challenging'
  },
  {
    id: '17',
    name: 'Japanese Alps',
    country: 'Japan',
    continent: 'asia',
    vacationType: ['mountains'],
    description: 'Stunning mountain ranges offering excellent skiing, hot springs, and traditional mountain villages.',
    temperature: 'cold',
    bestMonths: ['June', 'July', 'August', 'December', 'January', 'February'],
    imageQuery: 'japanese alps mountains village',
    budget: 'moderate',
    activities: ['Skiing', 'Onsen', 'Hiking', 'Traditional Villages'],
    highlights: ['Takayama', 'Shirakawa-go', 'Kamikochi', 'Snow Monkeys'],
    travelTip: 'Visit Shirakawa-go for traditional gassho houses. Try onsen after hiking.',
    flightDuration: '10+',
    difficulty: 'moderate'
  },
  {
    id: '18',
    name: 'Cameron Highlands',
    country: 'Malaysia',
    continent: 'asia',
    vacationType: ['mountains'],
    description: 'Cool mountain retreat with rolling tea plantations, strawberry farms, and colonial-era charm.',
    temperature: 'cool',
    bestMonths: ['February', 'March', 'April', 'July', 'August'],
    imageQuery: 'cameron highlands malaysia tea plantation',
    budget: 'budget',
    activities: ['Tea Factory Tours', 'Hiking', 'Strawberry Picking', 'Waterfall Visits'],
    highlights: ['BOH Tea Plantation', 'Mossy Forest', 'Strawberry Farms', 'Butterfly Garden'],
    travelTip: 'Visit tea plantations early morning. Bring layers for cool mountain weather.',
    flightDuration: '10+',
    difficulty: 'easy'
  },
  {
    id: '19',
    name: 'New York City',
    country: 'USA',
    continent: 'north america',
    vacationType: ['city break'],
    description: 'The city that never sleeps, featuring iconic landmarks, world-class museums, and diverse neighborhoods.',
    temperature: 'warm',
    bestMonths: ['April', 'May', 'June', 'September', 'October'],
    imageQuery: 'new york city skyline',
    budget: 'luxury',
    activities: ['Museum Visits', 'Broadway Shows', 'Shopping', 'Dining'],
    highlights: ['Statue of Liberty', 'Central Park', 'Times Square', 'Brooklyn Bridge'],
    travelTip: 'Get CityPASS for attractions. Use subway for easy transport.',
    flightDuration: '4-10'
  },
  {
    id: '22',
    name: 'Cancún',
    country: 'Mexico',
    continent: 'north america',
    vacationType: ['sea'],
    description: 'A tropical paradise with pristine Caribbean beaches, ancient Mayan ruins, and crystal-clear cenotes.',
    temperature: 'hot',
    bestMonths: ['December', 'January', 'February', 'March', 'April'],
    imageQuery: 'cancun mexico caribbean beach',
    budget: 'moderate',
    activities: ['Snorkeling', 'Mayan Ruins', 'Cenote Swimming', 'Beach Clubs'],
    highlights: ['Chichen Itza', 'Tulum Ruins', 'Isla Mujeres', 'Cenote Ik Kil'],
    travelTip: 'Visit cenotes for unique swimming experience. Book all-inclusive for value.',
    flightDuration: '4-10'
  },
  {
    id: '25',
    name: 'Rocky Mountains',
    country: 'Canada',
    continent: 'north america',
    vacationType: ['mountains'],
    description: 'Spectacular mountain range offering world-class skiing, hiking, and wildlife viewing.',
    temperature: 'cold',
    bestMonths: ['June', 'July', 'August', 'December', 'January', 'February'],
    imageQuery: 'rocky mountains canada lake',
    budget: 'moderate',
    activities: ['Hiking', 'Wildlife Watching', 'Skiing', 'Lake Activities'],
    highlights: ['Lake Louise', 'Banff', 'Jasper', 'Moraine Lake'],
    travelTip: 'Book accommodation early. Visit Moraine Lake before 6am to avoid crowds.',
    flightDuration: '4-10',
    difficulty: 'moderate'
  },
  {
    id: '28',
    name: 'Marrakech',
    country: 'Morocco',
    continent: 'africa',
    vacationType: ['city break'],
    description: 'An exotic city of bustling souks, stunning palaces, and beautiful gardens.',
    temperature: 'warm',
    bestMonths: ['March', 'April', 'May', 'October', 'November'],
    imageQuery: 'marrakech morocco medina',
    budget: 'budget',
    activities: ['Souk Shopping', 'Palace Tours', 'Hammam', 'Food Tours'],
    highlights: ['Jemaa el-Fnaa', 'Majorelle Garden', 'Bahia Palace', 'Medina Souks'],
    travelTip: 'Bargain in souks. Stay in a traditional riad for authentic experience.',
    flightDuration: '0-4'
  },
  {
    id: '31',
    name: 'Zanzibar',
    country: 'Tanzania',
    continent: 'africa',
    vacationType: ['sea'],
    description: 'A tropical archipelago with pristine white sand beaches and rich cultural heritage.',
    temperature: 'hot',
    bestMonths: ['June', 'July', 'August', 'September', 'October'],
    imageQuery: 'zanzibar tanzania beach',
    budget: 'moderate',
    activities: ['Snorkeling', 'Spice Tours', 'Stone Town Exploring', 'Dolphin Watching'],
    highlights: ['Stone Town', 'Nungwi Beach', 'Spice Plantations', 'Jozani Forest'],
    travelTip: 'Combine with safari on mainland. Visit Stone Town for history and culture.',
    flightDuration: '4-10'
  },
  {
    id: '36',
    name: 'Mount Kilimanjaro',
    country: 'Tanzania',
    continent: 'africa',
    vacationType: ['mountains'],
    description: 'Africa\'s highest peak offering the ultimate trekking challenge.',
    temperature: 'cool',
    bestMonths: ['January', 'February', 'July', 'August', 'September'],
    imageQuery: 'mount kilimanjaro tanzania',
    budget: 'luxury',
    activities: ['Mountain Climbing', 'Wildlife Viewing', 'Photography', 'Cultural Tours'],
    highlights: ['Uhuru Peak', 'Machame Route', 'Marangu Route', 'Coffee Plantations'],
    travelTip: 'Choose longer routes for better acclimatization. Train beforehand.',
    flightDuration: '4-10',
    difficulty: 'challenging'
  },
  {
    id: '37',
    name: 'Sydney',
    country: 'Australia',
    continent: 'oceania',
    vacationType: ['city break'],
    description: 'A stunning harbor city with iconic landmarks and beautiful beaches.',
    temperature: 'warm',
    bestMonths: ['September', 'October', 'November', 'March', 'April'],
    imageQuery: 'sydney opera house harbour',
    budget: 'moderate',
    activities: ['Harbor Cruises', 'Beach Hopping', 'Opera Shows', 'Coastal Walks'],
    highlights: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'The Rocks'],
    travelTip: 'Do the Bondi to Coogee coastal walk. Climb Harbour Bridge for views.',
    flightDuration: '10+'
  },
  {
    id: '40',
    name: 'Great Barrier Reef',
    country: 'Australia',
    continent: 'oceania',
    vacationType: ['sea'],
    description: 'The world\'s largest coral reef system offering incredible diving and snorkeling.',
    temperature: 'warm',
    bestMonths: ['June', 'July', 'August', 'September', 'October'],
    imageQuery: 'great barrier reef australia coral',
    budget: 'luxury',
    activities: ['Scuba Diving', 'Snorkeling', 'Island Hopping', 'Marine Life Tours'],
    highlights: ['Coral Gardens', 'Heart Reef', 'Whitehaven Beach', 'Marine Wildlife'],
    travelTip: 'Stay in Cairns or Port Douglas. Take liveaboard for best diving experience.',
    flightDuration: '24+ hours from Europe'
  },
  {
    id: '43',
    name: 'Southern Alps',
    country: 'New Zealand',
    continent: 'oceania',
    vacationType: ['mountains'],
    description: 'Spectacular mountain range home to Aoraki/Mount Cook and stunning fjords.',
    temperature: 'cold',
    bestMonths: ['December', 'January', 'February', 'June', 'July'],
    imageQuery: 'southern alps new zealand mount cook',
    budget: 'moderate',
    activities: ['Hiking', 'Glacier Walks', 'Skiing', 'Scenic Flights'],
    highlights: ['Mount Cook', 'Franz Josef Glacier', 'Milford Sound', 'Queenstown'],
    travelTip: 'Rent a campervan for flexibility. Book Milford Sound cruise in advance.',
    flightDuration: '24+ hours from Europe',
    difficulty: 'moderate'
  }
];

export const getAllDestinations = (): Destination[] => {
  return destinationDatabase;
};